export const products = [

  {
    id: 1,
    title: "Rhode Island Novelty 80 Piece Marble Run",
    price: "$11.75",
    originalPrice: "$12.47",
    image: "https://m.media-amazon.com/images/I/61DZ8vvCwUL._AC_SL1000_.jpg",
    amazonLink: "https://amzn.to/4s0cUhk",
    rating: 3.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 2,
    title: "Gecko Run Marble Run Starter Set by Thames & Kosmos, Toy of The Year Winner - 63 Piece Vertical Marble Run, Flexible Tracks | Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads, Creative Play",
    price: "$18.08",
    originalPrice: "$34.95",
    image: "https://m.media-amazon.com/images/I/81QmsYdK-aL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/414qtS3",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 3,
    title: "Blue Marble Bouncy Ball Science Kit - Make Up to 45 Glow in The Dark Bouncy Balls for Kids with 6 Colors & 5 Mold Shapes, DIY STEM Projects, Science Kit, Kids Science Projects",
    price: "$13.49",
    originalPrice: "$15.99",
    image: "https://m.media-amazon.com/images/I/81NFdbarawL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4uZ0oBC",
    rating: 4.2,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 4,
    title: "VTech Marble Rush 3-Point Launch Set with Mini Basketball Hoop",
    price: "$17.99",
    originalPrice: "$28.78",
    image: "https://m.media-amazon.com/images/I/61xx52qAdyL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3O3JFwi",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 5,
    title: "Ravensburger GraviTrax: Trampoline Accessory | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Accessory for 2019 Toy of The Year Finalist",
    price: "$6.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/51dQKrVj5cL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4sI5lxd",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 6,
    title: "Ravensburger GraviTrax: Spiral Accessory | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$7.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/51dVyRuT2QL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/3NLlzX8",
    rating: 4.8,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 7,
    title: "Ravensburger GraviTrax: Magnetic Cannon Accessory | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Accessory for 2019 Toy of The Year Finalist",
    price: "$7.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/51krhTYePaL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4m5VWNu",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 8,
    title: "Gecko Run Marble Run Rapid-Fire Launcher Expansion Pack | Thames & Kosmos, Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads, Hours of Creative Play",
    price: "$15.30",
    originalPrice: "$17.95",
    image: "https://m.media-amazon.com/images/I/71UwG2y+wjL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3Pu9KoR",
    rating: 4.8,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 9,
    title: "Rhode Island Novelty 45 Piece Marble Run",
    price: "$16.68",
    originalPrice: "$25.73",
    image: "https://m.media-amazon.com/images/I/61KZCgn-ocL._AC_SL1000_.jpg",
    amazonLink: "https://amzn.to/4t9ONhb",
    rating: 3.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 10,
    title: "Gecko Run Marble Run Flex-Corner Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads, Hours of Creative Play",
    price: "$12.56",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71t7A5jxptL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/410nMRu",
    rating: 3.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 11,
    title: "Ravensburger GraviTrax: Transfer Accessory | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$9.99",
    originalPrice: "$16.04",
    image: "https://m.media-amazon.com/images/I/71T8JbSz3DL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/41yMit0",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 12,
    title: "Gecko Run Marble Run Twister Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads for Hours of Creative Play",
    price: "$13.95",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71xQmhWiWxL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tgSWjz",
    rating: 4.1,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 13,
    title: "Ravensburger GraviTrax Junior: Jump Element | Encourages Experimentation and Creativity | Globally Recognized Brand | Ideal for Kids Ages 3 and Up",
    price: "$8.39",
    originalPrice: "$10.31",
    image: "https://m.media-amazon.com/images/I/5158fHqZLpL._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/4tczuEq",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 14,
    title: "Ravensburger GraviTrax: Jumper Accessory | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$6.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/71rfFEqgqaL._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/4dzS7xV",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 15,
    title: "Gecko Run Marble Run Speed-Kick Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads, Hours of Creative Play",
    price: "$14.95",
    originalPrice: "$19.07",
    image: "https://m.media-amazon.com/images/I/71epQyGKNaL._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/4sD2Uvz",
    rating: 3.9,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 16,
    title: "Gecko Run Marble Run Loop Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads for Hours of Creative Play",
    price: "$13.95",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71Y6l4WrvQL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3QcVYHe",
    rating: 4.1,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 17,
    title: "Ravensburger GraviTrax: Loop Accessory | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Accessory for 2019 Toy of The Year Finalist",
    price: "$9.99",
    originalPrice: "$15.99",
    image: "https://m.media-amazon.com/images/I/61w5sLWm4GL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4djw3aB",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 18,
    title: "Learning Resources STEM Explorers Marble Runners - 18 Pieces, Ages 5+ STEM Toys and Activities for Kids, Brain Teaser Toys and Games, Kindergarten Games",
    price: "$16.49",
    originalPrice: "$20.99",
    image: "https://m.media-amazon.com/images/I/81g3gw2rUxL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bYJBWJ",
    rating: 3.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 19,
    title: "Gecko Run Marble Run Snake Expansion Pack by Thames & Kosmos - Extra Zigzag Maze for Vertical Marble Run Starter Set; Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads for Hours of Creative Play",
    price: "$13.95",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71RKWsjgdOL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3NSVG7S",
    rating: 4.1,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 20,
    title: "Sunny Days Entertainment TOYMENDOUS 50 Piece Marbles - Colorful Glass Marble for Kids Games | 49 Player Marbles and 1 Shooter",
    price: "$3.84",
    originalPrice: "$4.99",
    image: "https://m.media-amazon.com/images/I/8185pfa1+RL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3OhA6df",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 21,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - Construction Set with 15 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$36.17",
    originalPrice: "$37.99",
    image: "https://m.media-amazon.com/images/I/91PPS5Nb5LL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tdOi5K",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 22,
    title: "National Geographic Magnetic Marble Run - 75-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project",
    price: "$42.58",
    originalPrice: "$44.99",
    image: "https://m.media-amazon.com/images/I/91w6fC9vIZL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/417mHHK",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 23,
    title: "National Geographic Marble Run with Motorized Elevator - 95-Piece Marble Maze Kit with Motorized Spiral Lift, 20 Marbles, Perpetual Motion Machine, STEM Gifts for Boys and Girls, Kids Physics Toys",
    price: "$29.49",
    originalPrice: "$34.99",
    image: "https://m.media-amazon.com/images/I/915k6RmVXEL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bQjlNW",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 24,
    title: "TOMY Screwball Scramble Level Up Marble Maze - Vertical Beat-The-Clock Marble Run Game - Skill & Dexterity Challenge - 1-4 Players - Ages 5+",
    price: "$27.17",
    originalPrice: "$28.99",
    image: "https://m.media-amazon.com/images/I/710sFcAe6eL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v5kmuv",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 25,
    title: "National Geographic Marble Run with Motorized Elevator - 150-Piece Marble Maze Kit with Motorized Spiral Lift, 30 Marbles, Storage Bag & More, Perpetual Motion Machine, Kids Physics Toys",
    price: "$37.49",
    originalPrice: "$49.99",
    image: "https://m.media-amazon.com/images/I/91SOwfn94dL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dhDu1Y",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 26,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - Construction Set with 15 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$36.17",
    originalPrice: "$37.99",
    image: "https://m.media-amazon.com/images/I/91PPS5Nb5LL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4c5IhBv",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 27,
    title: "National Geographic Marble Run with Motorized Elevator - 95-Piece Marble Maze Kit with Motorized Spiral Lift, 20 Marbles, Perpetual Motion Machine, STEM Gifts for Boys and Girls, Kids Physics Toys",
    price: "$29.49",
    originalPrice: "$34.99",
    image: "https://m.media-amazon.com/images/I/915k6RmVXEL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4vaPxoq",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 28,
    title: "Ravensburger GraviTrax Starter Set - Gravity & Magnetic Marble Game - MESH Accredited STEM Toy for Kids - Brain-Building, Educational Gift - Engages Critical Thinking, Problem Solving - Ages 8+",
    price: "$48.99",
    originalPrice: "$69.99",
    image: "https://m.media-amazon.com/images/I/616rhJ28XoL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4tH9EsP",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 29,
    title: "Magnetic Marble Run, Assorted Colors, 9.6 W x 11.2 H Magnetic Board, 34 Pieces",
    price: "$34.94",
    originalPrice: "$34.94",
    image: "https://m.media-amazon.com/images/I/71FhgmokFqL._SL1500_.jpg",
    amazonLink: "https://amzn.to/4m1GuBQ",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 30,
    title: "Rhode Island Novelty 45 Piece Marble Run",
    price: "$22.25",
    originalPrice: "$22.25",
    image: "https://m.media-amazon.com/images/I/61KZCgn-ocL._AC_SL1000_.jpg",
    amazonLink: "https://amzn.to/41FW5O5",
    rating: 3.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 31,
    title: "VTech Marble Rush Raceway Set",
    price: "$34.29",
    originalPrice: "$35.99",
    image: "https://m.media-amazon.com/images/I/719sqWzU6WL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4c1gSAm",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 32,
    title: "National Geographic Magnetic Marble Run - 75-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project",
    price: "$42.58",
    originalPrice: "$44.99",
    image: "https://m.media-amazon.com/images/I/91w6fC9vIZL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v5mvX5",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 33,
    title: "Ravensburger GraviTrax: Trax Expansion Set | Enhance Your Marble Run Experience | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$20.99",
    originalPrice: "$29.99",
    image: "https://m.media-amazon.com/images/I/611AZddpQqL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/417WEjE",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 34,
    title: "Gecko Run Marble Run Challenge Edition by Thames & Kosmos | Vertical Marble Run w/Flexible Tracks, No-Mess Setup | Challenge Cards for a Head-to-Head Engineering Design Game for Teams or Solo Play",
    price: "$44.53",
    originalPrice: "$69.95",
    image: "https://m.media-amazon.com/images/I/81pdRMbOqtL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4c1ASms",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 35,
    title: "VTech Marble Rush Launchpad Set",
    price: "$41.99",
    originalPrice: "$46.66",
    image: "https://m.media-amazon.com/images/I/81Mz6wtYjbS._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/47vN7GI",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 36,
    title: "ThinkFun Gravity Maze - Falling Marble Logic Game - Challenging STEM Toy for Kids 8-12 - Gravity Marble Maze - Brain-Building Fun - Educational Gift - Boosts Critical Thinking & Problem Solving",
    price: "$22.75",
    originalPrice: "$29.99",
    image: "https://m.media-amazon.com/images/I/81iwJf07veL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dWUF9h",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 37,
    title: "National Geographic Glowing Marble Run - 115 Piece Construction Set with 25 Glow in The Dark Glass Marbles, Storage Bag, Great Creative STEM Toy for Girls and Boys",
    price: "$32.39",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/91DeE+gskAL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/47xl5un",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 38,
    title: "Ravensburger GraviTrax Junior Extension - Multi Routes | Expandable Marble Run | Boost Motor Skills & Creativity | Ages 3+",
    price: "$24.49",
    originalPrice: "$34.99",
    image: "https://m.media-amazon.com/images/I/61KD3qSiHwL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/3PKbb2v",
    rating: 4.9,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 39,
    title: "Ravensburger GraviTrax: Lifter Expansion Set | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$20.99",
    originalPrice: "$29.99",
    image: "https://m.media-amazon.com/images/I/61kMgAfOC3L._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4djBWEJ",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 40,
    title: "Ravensburger GraviTrax PRO: Vertical Expansion Set - Advanced Marble Run STEM Toy | Encourages Experimentation and Creativity | Compatible with All GraviTrax Systems | Gift for Kids Ages 8+",
    price: "$23.09",
    originalPrice: "$32.99",
    image: "https://m.media-amazon.com/images/I/61i0ff1UnWL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4v5foxK",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 41,
    title: "National Geographic Magnetic Marble Run - 150-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project (Amazon Exclusive)",
    price: "$59.49",
    originalPrice: "$79.99",
    image: "https://m.media-amazon.com/images/I/71LmJAu6hqL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tofIpL",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 42,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - 250 Piece Construction Set with 50 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$89.99",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/91ClLMT4eKL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v2Gg1k",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 43,
    title: "VTech Marble Rush T-Rex Dino Thrill Track Set",
    price: "$56.75",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/81u2cy5X0aL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dttqTL",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 44,
    title: "VTech Marble Rush Ultimate Set",
    price: "$56.35",
    originalPrice: "$64.99",
    image: "https://m.media-amazon.com/images/I/81itE4jtCuS._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dWuy28",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 45,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - 250 Piece Construction Set with 50 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$89.99",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/91ClLMT4eKL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/47CdWsR",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 46,
    title: "National Geographic Magnetic Marble Run - 150-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project (Amazon Exclusive)",
    price: "$59.49",
    originalPrice: "$79.99",
    image: "https://m.media-amazon.com/images/I/71LmJAu6hqL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3NZetOD",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 47,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - 150 Piece Construction Set with 30 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$69.99",
    originalPrice: "$69.99",
    image: "https://m.media-amazon.com/images/I/91860gHgYyL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v3FeCb",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 48,
    title: "VTech Marble Rush Ultimate Set",
    price: "$56.35",
    originalPrice: "$64.99",
    image: "https://m.media-amazon.com/images/I/81itE4jtCuS._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/47vR0LO",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 49,
    title: "Ravensburger GraviTrax: XXL Starter Set | Innovative Marble Run & STEM Toy for Kids | Engaging & Educational Building Game",
    price: "$90.99",
    originalPrice: "$129.99",
    image: "https://m.media-amazon.com/images/I/81Ek+9EbdaL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bXLhj8",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 50,
    title: "Ravensburger GraviTrax PRO Starter Set - Gravity & Magnetic Marble Game - MESH Accredited STEM Toy for Kids - Brain-Building, Educational Gift - Engages Critical Thinking, Problem Solving - Ages 8+",
    price: "$73.92",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/81h9dYmyHKL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4cjMTVF",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 51,
    title: "Gecko Run Marble Run Deluxe Starter Set by Thames & Kosmos - Vertical Marble Run w/Flexible Tracks, Loop & Trampoline Tricks, Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads for Creative Play",
    price: "$59.06",
    originalPrice: "$59.06",
    image: "https://m.media-amazon.com/images/I/817GMPZTb9L._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4ciXpfQ",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 52,
    title: "VTech Marble Rush T-Rex Dino Thrill Track Set",
    price: "$56.75",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/81u2cy5X0aL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3NZTnQm",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 53,
    title: "The Learning Journey: Techno Gears Marble Mania - Extreme Glo (200+ pcs) - Glow in The Dark Marble Run for Kids Ages 8-14 Years - Award Winning Toys",
    price: "$59.99",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/91OsGJMwePL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tqpEza",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 54,
    title: "K'NEX - Marble Coaster Run with Motor, 504 Pieces, STEM Building, Kid Construction Set, Ages 8+",
    price: "$63.99",
    originalPrice: "$63.99",
    image: "https://m.media-amazon.com/images/I/81crDO2gKxL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bYSTlz",
    rating: 4.2,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 55,
    title: "Ravensburger GraviTrax PRO Starter-Set Drop'n'Roll. Interactive Marble Run System, Construction Toy for Children from 8 Years. Can be Combined with All Product Lines",
    price: "$82.50",
    originalPrice: "$99.99",
    image: "https://m.media-amazon.com/images/I/81jP1I+mbbL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3PMeSEK",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 56,
    title: "Ravensburger GraviTrax Junior Starter Set XXL - My Planet - Fun and Educational Preschool Marble Run Building Experience - STEM-Friendly, Interactive Learning, MESH Accredited - Kids Age 3 and Older",
    price: "$81.89",
    originalPrice: "$129.99",
    image: "https://m.media-amazon.com/images/I/91rPF4iPc9L._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4m43QqD",
    rating: 4.8,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 57,
    title: "Hape Wooden Quadrilla Super Spirals Marble Run STEM Toy for Kids 4+ Years",
    price: "$149.99",
    originalPrice: "$149.99",
    image: "https://m.media-amazon.com/images/I/617vGgKJ8NL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/41G34qh",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 58,
    title: "Hape Wooden Quadrilla Marble Run Vertigo Construction with Instruction | 134-PIECE STEM Educational Learning Toys for Kids",
    price: "$89.99",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/61eOMEhNyrL._AC_SL1195_.jpg",
    amazonLink: "https://amzn.to/4t50vud",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 59,
    title: "ROKR 3D Wooden Puzzles for Adults Marble Run Model Building Kit(LGA01 Marble Night City)",
    price: "$70.37",
    originalPrice: "$70.37",
    image: "https://m.media-amazon.com/images/I/81diukhc-UL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4ckF7Le",
    rating: 4.3,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 60,
    title: "Ravensburger - GraviTrax - Speed Starter Set (185 Pieces) - Marble Run - Creative Construction Toy - Build-Your-Own Marble Track - Ages 8 and Up",
    price: "$111.63",
    originalPrice: "$111.63",
    image: "https://m.media-amazon.com/images/I/81iEVe-sEjL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3PNuTKE",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: "Best Seller",
    currency: "USD",
  },
  {
  id: 61,
  title: "Blix Marble Run - 1, 118 Piece Construction Set, Design and Build Your Own Tracks, Marble Run Toys for Kids, Compatible with Other Brick Brands, Ages 5+, Made in India",
  price: "₹826",
  originalPrice: "₹939",
  image: "https://m.media-amazon.com/images/I/818iaoyW9KL._SL1500_.jpg",
  amazonLink: "https://amzn.to/47H9ybV",
  rating: 4.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 62,
  title: "Blix Marble Run 2 | Motorised Conveyor, 4+Models, Age-8+, Best Gift for Kids",
  price: "₹1,759",
  originalPrice: "₹1,999",
  image: "https://m.media-amazon.com/images/I/81gestHrinL._SL1500_.jpg",
  amazonLink: "https://amzn.to/47GzZ1z",
  rating: 4.1,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 63,
  title: "Kidology 3D Marble Run DIY Construction Building Blocks Toys for Kids Marble Race Track Play Set (142 PCs)",
  price: "₹1,498.98",
  originalPrice: "₹4,599",
  image: "https://m.media-amazon.com/images/I/71lDKv7p-RL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sfyoqW",
  rating: 4.3,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 64,
  title: "Wooden Haba Marble Run Track with 8 Multicolor Balls | Montessori STEM Toy",
  price: "₹999",
  originalPrice: "₹3,000",
  image: "https://m.media-amazon.com/images/I/71H5Fs+DliL._SL1500_.jpg",
  amazonLink: "https://amzn.to/41Ln36Y",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 65,
  title: "Chanak 48 PCS Magnetic Tiles Building Set for Kids, STEM Educational Toy",
  price: "₹782",
  originalPrice: "₹2,999",
  image: "https://m.media-amazon.com/images/I/81atsU8J6lL._SL1500_.jpg",
  amazonLink: "https://amzn.to/47Haqxd",
  rating: 3.5,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 66,
  title: "Chocozone Marble Run Track 108 Piece Marble Maze Building Set",
  price: "₹789",
  originalPrice: "₹1,499",
  image: "https://m.media-amazon.com/images/I/71hfBRrIawL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4v9Tk5d",
  rating: 4.0,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 67,
  title: "Storio Magnetic Ball Runner Tiles Building Set for Kids (25 PCS)",
  price: "₹499",
  originalPrice: "₹1,099",
  image: "https://m.media-amazon.com/images/I/610dBn1Q-GL._SL1080_.jpg",
  amazonLink: "https://amzn.to/4sPuwxL",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 68,
  title: "Butterfly EduFields 5in1 STEM Robotics Kit for Kids | No Coding Required",
  price: "₹997",
  originalPrice: "₹1,299",
  image: "https://m.media-amazon.com/images/I/816zf6oGygL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4bOLaaP",
  rating: 3.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 69,
  title: "Heattack 48pcs Magnetic Building Blocks for Kids – STEM Toy Set",
  price: "₹999",
  originalPrice: "₹3,999",
  image: "https://m.media-amazon.com/images/I/61vIErxKHyL.jpg",
  amazonLink: "https://amzn.to/3Qh0fcG",
  rating: 3.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 70,
  title: "Wooden Marble Track Game Smiley Face Ball Slider Tree",
  price: "₹299",
  originalPrice: "₹700",
  image: "https://m.media-amazon.com/images/I/41n-0icmwEL._SL1080_.jpg",
  amazonLink: "https://amzn.to/4maMB74",
  rating: 4.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 71,
  title: "SHIYO Magnetic Tiles for Kids Educational Building Blocks (32 Pieces)",
  price: "₹859",
  originalPrice: "₹1,399",
  image: "https://m.media-amazon.com/images/I/81FR1ax-3ML._SL1500_.jpg",
  amazonLink: "https://amzn.to/4m5TshQ",
  rating: 4.8,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 72,
  title: "Spiral Slide 4 Level Ball Rolling Ramp Toy for Kids",
  price: "₹820",
  originalPrice: "₹1,200",
  image: "https://m.media-amazon.com/images/I/31PaOiyXC3L.jpg",
  amazonLink: "https://amzn.to/3PQFUuG",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 73,
  title: "Magnetic Tiles 28Pcs 3D Building Block Set for Kids STEM Toy",
  price: "₹849",
  originalPrice: "₹3,599",
  image: "https://m.media-amazon.com/images/I/81SvefOe0xL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sSgMT9",
  rating: 4.3,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 74,
  title: "Light Magnetic Tiles Building Blocks for Kids (49 Pc)",
  price: "₹1,549",
  originalPrice: "₹2,499",
  image: "https://m.media-amazon.com/images/I/61j7FChLjBL.jpg",
  amazonLink: "https://amzn.to/41KFNDD",
  rating: 4.1,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 75,
  title: "88 Pcs Building Blocks Funnel Slide DIY Marble Run Set",
  price: "₹499",
  originalPrice: "₹899",
  image: "https://m.media-amazon.com/images/I/713j4j8OXGL._SL1500_.jpg",
  amazonLink: "https://amzn.to/3PZvF7m",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 76,
  title: "Toyshine 85Pc DIY Marble Run Building Blocks for Kids",
  price: "₹981",
  originalPrice: "₹1,365",
  image: "https://m.media-amazon.com/images/I/71tbZZWkyWL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sdnUZ0",
  rating: 3.8,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 77,
  title: "Wooden Marble Run Track Sea Wave 4-Line Maze Montessori Toy",
  price: "₹2,999",
  originalPrice: "₹2,999",
  image: "https://m.media-amazon.com/images/I/71NT8jpgFpL._SL1067_.jpg",
  amazonLink: "https://amzn.to/3POwRKT",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 78,
  title: "Light Magnetic Tiles 110 Pcs 3D STEAM Educational Toys",
  price: "₹3,890",
  originalPrice: "₹4,999",
  image: "https://m.media-amazon.com/images/I/71jXFEQ+bXL._SL1000_.jpg",
  amazonLink: "https://amzn.to/3NLB1CF",
  rating: 4.1,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 79,
  title: "Heattack Olly's Magnetic Blocks 100 Pieces Set for Kids",
  price: "₹2,589",
  originalPrice: "₹5,999",
  image: "https://m.media-amazon.com/images/I/81lpjlddxEL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4s8VAqN",
  rating: 4.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 80,
  title: "GELTILES Imagination 100 Pcs Magnetic Tiles Set for Kids",
  price: "₹4,999",
  originalPrice: "₹7,999",
  image: "https://m.media-amazon.com/images/I/818LVQpBw0L._SL1500_.jpg",
  amazonLink: "https://amzn.to/4s8zjsZ",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},

{
  id: 81,
  title: "Big Size Blocks Marble Run Slide Building Toys LED Track (186 Pcs)",
  price: "₹2,499",
  originalPrice: "₹4,999",
  image: "https://m.media-amazon.com/images/I/81T6bSdP7lL._SL1500_.jpg",
  amazonLink: "https://amzn.to/41cvp7y",
  rating: 4.5,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 82,
  title: "Quercetti Skyrail Jurassic Marble Run Toy for Kids",
  price: "₹2,499",
  originalPrice: "₹2,499",
  image: "https://m.media-amazon.com/images/I/61+xHfjELfL._SL1001_.jpg",
  amazonLink: "https://amzn.to/4sLXoqB",
  rating: 4.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 83,
  title: "60 Pieces Wooden Classic Marble Run Track for Kids",
  price: "₹2,849",
  originalPrice: "₹4,499",
  image: "https://m.media-amazon.com/images/I/61PVVirll6L._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sbmCxq",
  rating: 4.1,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 84,
  title: "Heattack Falitic 100 PCS Advanced Magnetic Tiles Set",
  price: "₹2,595",
  originalPrice: "₹5,999",
  image: "https://m.media-amazon.com/images/I/61l3GtgIPwL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4tsJlGt",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 85,
  title: "KIPA GAMING Magnetic Tiles 76 Pcs STEM Building Set",
  price: "₹2,699",
  originalPrice: "₹4,999",
  image: "https://m.media-amazon.com/images/I/71bJ0Xw4DJL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4ccXUXU",
  rating: 4.3,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 86,
  title: "Deluxe 100 Piece Colorful Magnetic Tile Play Set",
  price: "₹2,399",
  originalPrice: "₹5,999",
  image: "https://m.media-amazon.com/images/I/51vyvKPrOKL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4cmA5Oq",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 87,
  title: "70 Pieces Large Magnetic Tiles 3D Building Blocks Set",
  price: "₹2,745",
  originalPrice: "₹7,999",
  image: "https://m.media-amazon.com/images/I/511Y-P7PX7L._SX300_SY300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4coee9i",
  rating: 3.7,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 88,
  title: "Magnetic Tiles 100PCS Magnet Building Blocks Set",
  price: "₹2,399",
  originalPrice: "₹5,999",
  image: "https://m.media-amazon.com/images/I/81EkgUehoAL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sVI76M",
  rating: 4.7,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 89,
  title: "NESTA TOYS Marble Parkour Mechanical Model Kit",
  price: "₹2,799",
  originalPrice: "₹3,499",
  image: "https://m.media-amazon.com/images/I/51xLFy0SsiL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4dnBmFZ",
  rating: 3.0,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 90,
  title: "243-Piece Big Size Marble Run Building Set LED Track",
  price: "₹2,899",
  originalPrice: "₹4,999",
  image: "https://m.media-amazon.com/images/I/81T6bSdP7lL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sOIaRD",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 91,
  title: "CONNETIX Magnetic Tiles Pastel Starter Pack, 64 Pieces",
  price: "₹5,390",
  originalPrice: "₹8,999",
  image: "https://m.media-amazon.com/images/I/71d-4IM1YbL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4m6lf1M",
  rating: 4.7,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 92,
  title: "GELTILES Kid Premium 150 PCS Building Blocks Toy with Storage Box",
  price: "₹7,490",
  originalPrice: "₹12,910",
  image: "https://m.media-amazon.com/images/I/51FCBo6cOVL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4dY8gx1",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 93,
  title: "National Geographic Magnetic Marble Run 50-Piece STEM Set",
  price: "₹6,024.53",
  originalPrice: "₹9,639.25",
  image: "https://m.media-amazon.com/images/I/91trq7GYW4L._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sb1iZa",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 94,
  title: "Glonova Marble Run Race Track with Glass for Kids, 127 Pieces",
  price: "₹6,853",
  originalPrice: "₹6,853",
  image: "https://m.media-amazon.com/images/I/81NX7p3SW8L._SL1500_.jpg",
  amazonLink: "https://amzn.to/3POBuEL",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 95,
  title: "Blue Marble National Geographic 150-Piece Motorized Marble Run Set",
  price: "₹15,068.51",
  originalPrice: "₹24,109.62",
  image: "https://m.media-amazon.com/images/I/81ecf2oRzZL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4c8oEbW",
  rating: 4.5,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 96,
  title: "133PCS Children Marble Run Set Interactive Development Toy",
  price: "₹6,569",
  originalPrice: "₹14,999",
  image: "https://m.media-amazon.com/images/I/51Q1UHtfZ-L._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4seP8yr",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 97,
  title: "National Geographic Glowing Marble Run 115 Piece Set",
  price: "₹12,377.64",
  originalPrice: "₹23,218.65",
  image: "https://m.media-amazon.com/images/I/51MhyBO835L._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/48b2fcG",
  rating: 4.7,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 98,
  title: "Marble Run 150pcs Glow in The Dark Track Set for Kids",
  price: "₹6,751",
  originalPrice: "₹21,272.55",
  image: "https://m.media-amazon.com/images/I/41ZkSFAhR6L._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4co7vw3",
  rating: 4.7,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 99,
  title: "UGEARS Marble Run Spiral Hoist Wooden Puzzle Kit",
  price: "₹6,090",
  originalPrice: "₹6,090",
  image: "https://m.media-amazon.com/images/I/81z+5Ofk5rL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sei5dN",
  rating: 4.1,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 100,
  title: "Marble Run Sensory Toy Race Track for Kids Style A",
  price: "₹6,645",
  originalPrice: "₹9,799",
  image: "https://m.media-amazon.com/images/I/31B4aNrCZ1L._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4trjizh",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 101,
  title: "Ravensburger GraviTrax Bridges Expansion Set",
  price: "₹6,783.26",
  originalPrice: "₹10,853.22",
  image: "https://m.media-amazon.com/images/I/61M38GMLvoL._SL1032_.jpg",
  amazonLink: "https://amzn.to/4bZzkcI",
  rating: 4.7,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 102,
  title: "Marble Run Sensory Toy Race Track for Kids Style B",
  price: "₹6,408",
  originalPrice: "₹9,699",
  image: "https://m.media-amazon.com/images/I/61QQEa26WfL._SL1500_.jpg",
  amazonLink: "https://amzn.to/47HoF59",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 103,
  title: "Marble Genius Marble Run Racing Set 125 Piece",
  price: "₹15,118",
  originalPrice: "₹36,600",
  image: "https://m.media-amazon.com/images/I/519x9zrEQHL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4co8nRl",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 104,
  title: "Marble Genius Extreme Set 125 Pieces + Glass Marbles",
  price: "₹26,023.12",
  originalPrice: "₹26,023.12",
  image: "https://m.media-amazon.com/images/I/51oIW-UgqHL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/41KYRS9",
  rating: 4.5,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 105,
  title: "Learning Resources Tumble Trax Magnetic Marble Run",
  price: "₹6,284",
  originalPrice: "₹15,800",
  image: "https://m.media-amazon.com/images/I/81LY8JvclmL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4dt5Nul",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 106,
  title: "ROKR Marble Night City Wooden Marble Run Puzzle Kit",
  price: "₹16,211",
  originalPrice: "₹16,211",
  image: "https://m.media-amazon.com/images/I/61zudyCghSL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4sOKlVk",
  rating: 4.3,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 107,
  title: "UGEARS Marble Run Chain Wooden Puzzle Kit",
  price: "₹12,079",
  originalPrice: "₹22,800",
  image: "https://m.media-amazon.com/images/I/51u23bQP9IL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4bUXKE4",
  rating: 4.5,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 108,
  title: "National Geographic Glowing Marble Run 250 Piece Set",
  price: "₹52,081",
  originalPrice: "₹56,423.25",
  image: "https://m.media-amazon.com/images/I/61eMGgnGHvL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/4dsUrqk",
  rating: 4.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 109,
  title: "Quercetti Marble League Marble Run Racing Set 228 Pieces",
  price: "₹10,786.96",
  originalPrice: "₹17,259.14",
  image: "https://m.media-amazon.com/images/I/51s+zPg00DL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/3PNH1vm",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 110,
  title: "JOYIN 140 Pcs Marble Run Premium Set STEM Learning Toy",
  price: "₹11,659",
  originalPrice: "₹26,410.80",
  image: "https://m.media-amazon.com/images/I/514XdKg5KbL._SY300_SX300_QL70_FMwebp_.jpg",
  amazonLink: "https://amzn.to/41KcPUj",
  rating: 4.5,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 111,
  title: "Blix Marble Run - 118 Piece Construction Set Made in India",
  price: "₹826",
  originalPrice: "₹939",
  image: "https://m.media-amazon.com/images/I/818iaoyW9KL._SL1500_.jpg",
  amazonLink: "https://amzn.to/47H9ybV",
  rating: 4.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 112,
  title: "Blix Marble Run 2 Motorised Conveyor Set",
  price: "₹1,759",
  originalPrice: "₹1,999",
  image: "https://m.media-amazon.com/images/I/81gestHrinL._SL1500_.jpg",
  amazonLink: "https://amzn.to/47GzZ1z",
  rating: 4.1,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 113,
  title: "Kidology 3D Marble Run DIY 142 Pieces STEM Toy",
  price: "₹1,498.98",
  originalPrice: "₹4,599",
  image: "https://m.media-amazon.com/images/I/71lDKv7p-RL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4sfyoqW",
  rating: 4.3,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 114,
  title: "Wooden Haba Marble Run Track with 8 Multicolor Balls",
  price: "₹999",
  originalPrice: "₹3,000",
  image: "https://m.media-amazon.com/images/I/71H5Fs+DliL._SL1500_.jpg",
  amazonLink: "https://amzn.to/41Ln36Y",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 115,
  title: "Chanak 48 PCS Magnetic Tiles Marble Run STEM Toy",
  price: "₹782",
  originalPrice: "₹2,999",
  image: "https://m.media-amazon.com/images/I/81atsU8J6lL._SL1500_.jpg",
  amazonLink: "https://amzn.to/47Haqxd",
  rating: 3.5,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 116,
  title: "Chocozone Marble Run Track 108 Piece STEM Set",
  price: "₹789",
  originalPrice: "₹1,499",
  image: "https://m.media-amazon.com/images/I/71hfBRrIawL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4v9Tk5d",
  rating: 4.0,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 117,
  title: "Storio Magnetic Ball Runner Tiles 25 PCS",
  price: "₹499",
  originalPrice: "₹1,099",
  image: "https://m.media-amazon.com/images/I/610dBn1Q-GL._SL1080_.jpg",
  amazonLink: "https://amzn.to/4sPuwxL",
  rating: 4.2,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 118,
  title: "Butterfly EduFields 5in1 STEM Robotics Kit",
  price: "₹997",
  originalPrice: "₹1,299",
  image: "https://m.media-amazon.com/images/I/816zf6oGygL._SL1500_.jpg",
  amazonLink: "https://amzn.to/4bOLaaP",
  rating: 3.6,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 119,
  title: "Heattack 48pcs Magnetic Building Blocks STEM Toy",
  price: "₹999",
  originalPrice: "₹3,999",
  image: "https://m.media-amazon.com/images/I/61vIErxKHyL.jpg",
  amazonLink: "https://amzn.to/3Qh0fcG",
  rating: 3.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
},
{
  id: 120,
  title: "Wooden Marble Track Game Smiley Face Ball Slider Toy",
  price: "₹299",
  originalPrice: "₹700",
  image: "https://m.media-amazon.com/images/I/41n-0icmwEL._SL1080_.jpg",
  amazonLink: "https://amzn.to/4maMB74",
  rating: 4.4,
  reviews: 3420,
  category: "Toys & Games",
  badge: "Best Seller",
  currency: "INR",
}
];

export const categories = ["All", ...new Set(products.map((p) => p.category))];