export const products = [
  {
    id: 1,
    title: "Rhode Island Novelty 80 Piece Marble Run",
    price: "$11.75",
    originalPrice: "$12.47",
    image: "https://m.media-amazon.com/images/I/61DZ8vvCwUL._AC_SL1000_.jpg",
    amazonLink: "https://amzn.to/4cc6mrl",
    rating: 3.0,
    reviews: 3420,
    category: "Marble Run Sets",
    badge: "Best Seller",
    currency: "USD",
  },
  {
    id: 2,
    title: "QUERCETTI Marble Run Classic 60-Piece Set",
    price: "₹2,999",
    originalPrice: "₹3,999",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=QUERCETTI+Marble+Run+Classic",
    rating: 4.6,
    reviews: 2180,
    category: "Marble Run Sets",
    badge: "Top Rated",
    currency: "INR",
  },
  {
    id: 3,
    title: "BRIO Marble Run Starter Set 34-Pieces",
    price: "₹3,499",
    originalPrice: "₹4,499",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=BRIO+Marble+Run+Starter+Set",
    rating: 4.7,
    reviews: 1890,
    category: "Marble Run Sets",
    badge: "New",
    currency: "INR",
  },
  {
    id: 4,
    title: "Melissa & Doug Suspend Family Game Marble Maze",
    price: "₹1,899",
    originalPrice: "₹2,599",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Melissa+Doug+Marble+Maze",
    rating: 4.5,
    reviews: 5670,
    category: "Marble Maze",
    badge: "Best Seller",
    currency: "INR",
  },
  {
    id: 5,
    title: "SmartGames Marble Circuit Puzzle 60 Challenges",
    price: "₹2,499",
    originalPrice: "₹3,299",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=SmartGames+Marble+Circuit",
    rating: 4.8,
    reviews: 4230,
    category: "Marble Puzzle",
    badge: "Top Rated",
    currency: "INR",
  },
  {
    id: 6,
    title: "Gravitrax Starter Set Marble Run Track System",
    price: "₹6,999",
    originalPrice: "₹8,999",
    image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Gravitrax+Starter+Set+Marble+Run",
    rating: 4.9,
    reviews: 7850,
    category: "STEM Marble Run",
    badge: "Deal",
    currency: "INR",
  },
  {
    id: 7,
    title: "Ravensburger Gravitrax Power Starter Set",
    price: "₹9,499",
    originalPrice: "₹12,999",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Ravensburger+Gravitrax+Power",
    rating: 4.7,
    reviews: 3100,
    category: "STEM Marble Run",
    badge: "Hot Deal",
    currency: "INR",
  },
  {
    id: 8,
    title: "Mega Marble Run 100-Piece Construction Set",
    price: "₹1,799",
    originalPrice: "₹2,999",
    image: "https://images.unsplash.com/photo-1533294455009-a77b7557d2d1?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Mega+Marble+Run+100+piece",
    rating: 4.3,
    reviews: 9870,
    category: "Marble Run Sets",
    badge: null,
    currency: "INR",
  },
  {
    id: 9,
    title: "Marble Genius Marble Run Super Set 130 Pieces",
    price: "₹3,799",
    originalPrice: "₹4,999",
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Marble+Genius+Super+Set+130",
    rating: 4.6,
    reviews: 6540,
    category: "Marble Run Sets",
    badge: null,
    currency: "INR",
  },
  {
    id: 10,
    title: "Galt Toys Giant Marble Run 80-Piece Set",
    price: "₹2,699",
    originalPrice: "₹3,699",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Galt+Toys+Giant+Marble+Run",
    rating: 4.4,
    reviews: 4320,
    category: "Marble Run Sets",
    badge: "Popular",
    currency: "INR",
  },
  {
    id: 11,
    title: "LEGO Classic 11009 Marbles Maze Building Kit",
    price: "₹3,299",
    originalPrice: "₹4,299",
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=LEGO+Classic+Marbles+Maze",
    rating: 4.7,
    reviews: 12400,
    category: "LEGO Marble",
    badge: null,
    currency: "INR",
  },
  {
    id: 12,
    title: "K'NEX Education Marble Maze Set 195 Pieces",
    price: "₹4,499",
    originalPrice: "₹5,999",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=KNEX+Education+Marble+Maze",
    rating: 4.5,
    reviews: 2780,
    category: "STEM Marble Run",
    badge: "Deal",
    currency: "INR",
  },
  {
    id: 13,
    title: "Hape Quadrilla Music Motion Marble Run",
    price: "₹5,499",
    originalPrice: "₹7,499",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Hape+Quadrilla+Music+Motion",
    rating: 4.8,
    reviews: 1560,
    category: "Marble Run Sets",
    badge: null,
    currency: "INR",
  },
  {
    id: 14,
    title: "ETA hand2mind Wood Marble Run 43-Piece STEM",
    price: "₹2,199",
    originalPrice: "₹3,199",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=ETA+hand2mind+Wood+Marble+Run",
    rating: 4.4,
    reviews: 3890,
    category: "Wooden Marble Run",
    badge: "Best Seller",
    currency: "INR",
  },
  {
    id: 15,
    title: "PicassoTiles Marble Run 40-Piece Race Track",
    price: "₹1,999",
    originalPrice: "₹2,799",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=PicassoTiles+Marble+Run+40+piece",
    rating: 4.3,
    reviews: 7230,
    category: "Marble Run Sets",
    badge: null,
    currency: "INR",
  },
  {
    id: 16,
    title: "Gravitrax Extension Track 40-Piece Add-On Set",
    price: "₹3,199",
    originalPrice: "₹4,199",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Gravitrax+Extension+Track+40+piece",
    rating: 4.6,
    reviews: 5430,
    category: "STEM Marble Run",
    badge: "Top Rated",
    currency: "INR",
  },
  {
    id: 17,
    title: "Siku Marble Run Glass Marbles 200-Pack Set",
    price: "₹599",
    originalPrice: "₹999",
    image: "https://images.unsplash.com/photo-1533294455009-a77b7557d2d1?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Glass+Marbles+200+Pack",
    rating: 4.5,
    reviews: 18900,
    category: "Marbles",
    badge: "Hot Deal",
    currency: "INR",
  },
  {
    id: 18,
    title: "Bruder Marble Chute Vertical Drop Tower Toy",
    price: "₹2,299",
    originalPrice: "₹3,299",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Marble+Chute+Vertical+Drop+Tower",
    rating: 4.2,
    reviews: 4560,
    category: "Marble Run Sets",
    badge: null,
    currency: "INR",
  },
  {
    id: 19,
    title: "Mindware Q-BA-MAZE 2.0 Big Box Marble Stunt",
    price: "₹3,999",
    originalPrice: "₹5,499",
    image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Mindware+Q-BA-MAZE+2.0+Big+Box",
    rating: 4.7,
    reviews: 2340,
    category: "Marble Stunt",
    badge: null,
    currency: "INR",
  },
  {
    id: 20,
    title: "Zig Zag Marble Run Wooden Tower 45-Piece",
    price: "₹1,599",
    originalPrice: "₹2,299",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Zig+Zag+Marble+Run+Wooden+Tower",
    rating: 4.1,
    reviews: 6780,
    category: "Wooden Marble Run",
    badge: null,
    currency: "INR",
  },
  {
    id: 21,
    title: "Tumble Trax Magnetic Marble Run 20-Piece Set",
    price: "₹2,799",
    originalPrice: "₹3,799",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Tumble+Trax+Magnetic+Marble+Run",
    rating: 4.5,
    reviews: 3210,
    category: "Magnetic Marble Run",
    badge: "Popular",
    currency: "INR",
  },
  {
    id: 22,
    title: "Hubelino Marble Run Pi 68-Piece Tower Set",
    price: "₹5,999",
    originalPrice: "₹7,999",
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Hubelino+Marble+Run+Pi+68+piece",
    rating: 4.8,
    reviews: 1890,
    category: "Marble Run Sets",
    badge: "Premium",
    currency: "INR",
  },
  {
    id: 23,
    title: "Edx Education Hollow Blocks Marble Run 65-Piece",
    price: "₹3,599",
    originalPrice: "₹4,799",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Edx+Education+Marble+Run+65+piece",
    rating: 4.4,
    reviews: 2100,
    category: "Marble Run Sets",
    badge: "Deal",
    currency: "INR",
  },
  {
    id: 24,
    title: "Gravitrax Volcano Marble Run Action Pack",
    price: "₹2,499",
    originalPrice: "₹3,499",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Gravitrax+Volcano+Action+Pack",
    rating: 4.6,
    reviews: 8900,
    category: "STEM Marble Run",
    badge: null,
    currency: "INR",
  },
  {
    id: 25,
    title: "Bigjigs Toys Rail Marble Run 38-Piece Wooden",
    price: "₹2,099",
    originalPrice: "₹2,999",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Bigjigs+Rail+Marble+Run+Wooden",
    rating: 4.3,
    reviews: 4320,
    category: "Wooden Marble Run",
    badge: null,
    currency: "INR",
  },
  {
    id: 26,
    title: "Marble Genius Run Add-On Extension Funnel Set",
    price: "₹1,299",
    originalPrice: "₹1,999",
    image: "https://images.unsplash.com/photo-1533294455009-a77b7557d2d1?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Marble+Genius+Add-On+Funnel+Set",
    rating: 4.2,
    reviews: 5600,
    category: "Marble Run Accessories",
    badge: null,
    currency: "INR",
  },
  {
    id: 27,
    title: "Elenco Marble Run Puzzle STEM Challenge 60 Piece",
    price: "₹2,999",
    originalPrice: "₹4,099",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Elenco+Marble+Run+STEM+60+piece",
    rating: 4.5,
    reviews: 3450,
    category: "STEM Marble Run",
    badge: "New",
    currency: "INR",
  },
  {
    id: 28,
    title: "Quercetti Marble Safari Run Animal Adventure Set",
    price: "₹1,799",
    originalPrice: "₹2,599",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Quercetti+Marble+Safari+Animal",
    rating: 4.3,
    reviews: 7800,
    category: "Marble Run Sets",
    badge: "Deal",
    currency: "INR",
  },
  {
    id: 29,
    title: "Hape Quadrilla Roundabout 98-Piece Marble Run",
    price: "₹7,499",
    originalPrice: "₹9,999",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Hape+Quadrilla+Roundabout+98+piece",
    rating: 4.9,
    reviews: 2300,
    category: "Marble Run Sets",
    badge: "Premium",
    currency: "INR",
  },
  {
    id: 30,
    title: "Marble Power Run Electric Motor Lifter Track Set",
    price: "₹4,999",
    originalPrice: "₹6,499",
    image: "https://images.unsplash.com/photo-1605870445919-838d190e8e1b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Marble+Power+Run+Electric+Motor",
    rating: 4.6,
    reviews: 1890,
    category: "Electric Marble Run",
    badge: "New",
    currency: "INR",
  },
  {
    id: 31,
    title: "Orb Factory Sticky Mosaics Marble Madness Run",
    price: "₹799",
    originalPrice: "₹1,499",
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Marble+Madness+Run+Starter",
    rating: 3.9,
    reviews: 9800,
    category: "Marble Run Sets",
    badge: "Budget Pick",
    currency: "INR",
  },
  {
    id: 32,
    title: "Learning Resources Gears! Marble Motion Set 100 Pc",
    price: "₹3,299",
    originalPrice: "₹4,499",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Learning+Resources+Gears+Marble+Motion",
    rating: 4.4,
    reviews: 6700,
    category: "STEM Marble Run",
    badge: null,
    currency: "INR",
  },
  {
    id: 33,
    title: "Toysmith Marble Works Deluxe 125-Piece Run Set",
    price: "₹2,599",
    originalPrice: "₹3,599",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Toysmith+Marble+Works+Deluxe+125",
    rating: 4.3,
    reviews: 5670,
    category: "Marble Run Sets",
    badge: "Top Rated",
    currency: "INR",
  },
  {
    id: 34,
    title: "Fat Brain Toys Marble Towers Gravity Defying Set",
    price: "₹3,899",
    originalPrice: "₹5,299",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Fat+Brain+Toys+Marble+Towers",
    rating: 4.7,
    reviews: 4500,
    category: "Marble Run Sets",
    badge: "Deal",
    currency: "INR",
  },
  {
    id: 35,
    title: "Amaze 16-Way Marble Puzzle Brain Teaser Run",
    price: "₹999",
    originalPrice: "₹1,699",
    image: "https://images.unsplash.com/photo-1533294455009-a77b7557d2d1?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Amaze+16-Way+Marble+Puzzle",
    rating: 4.1,
    reviews: 14300,
    category: "Marble Puzzle",
    badge: null,
    currency: "INR",
  },
  {
    id: 36,
    title: "Gravitrax Jumper Expansion Set Marble Track",
    price: "₹1,999",
    originalPrice: "₹2,799",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Gravitrax+Jumper+Expansion+Set",
    rating: 4.5,
    reviews: 3210,
    category: "STEM Marble Run",
    badge: "Popular",
    currency: "INR",
  },
  {
    id: 37,
    title: "Melissa & Doug Swirling Sophies Marble Tower",
    price: "₹1,499",
    originalPrice: "₹2,199",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Melissa+Doug+Swirling+Sophie+Marble",
    rating: 4.4,
    reviews: 8700,
    category: "Wooden Marble Run",
    badge: null,
    currency: "INR",
  },
  {
    id: 38,
    title: "Marble Works Tube Marble Run Set 122-Piece",
    price: "₹2,899",
    originalPrice: "₹3,999",
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Marble+Works+Tube+Run+122+piece",
    rating: 4.3,
    reviews: 4100,
    category: "Marble Run Sets",
    badge: null,
    currency: "INR",
  },
  {
    id: 39,
    title: "STEM Magnetic Marble Run Track 75-Piece Builder",
    price: "₹2,599",
    originalPrice: "₹3,499",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=STEM+Magnetic+Marble+Run+75+piece",
    rating: 4.6,
    reviews: 5900,
    category: "Magnetic Marble Run",
    badge: "Best Seller",
    currency: "INR",
  },
  {
    id: 40,
    title: "Hape Quadrilla Marble Run Dizzy Izzy 73-Piece",
    price: "₹6,499",
    originalPrice: "₹8,499",
    image: "https://images.unsplash.com/photo-1605870445919-838d190e8e1b?w=400&h=400&fit=crop",
    amazonLink: "https://www.amazon.in/s?k=Hape+Quadrilla+Dizzy+Izzy+73+piece",
    rating: 4.8,
    reviews: 2800,
    category: "Marble Run Sets",
    badge: "Premium",
    currency: "INR",
  },
  // --- Excel Data (id 41 onwards) ---
  {
    id: 41,
    title: "Rhode Island Novelty 80 Piece Marble Run",
    price: "$11.75",
    originalPrice: "$12.47",
    image: "https://m.media-amazon.com/images/I/61DZ8vvCwUL._AC_SL1000_.jpg",
    amazonLink: "https://amzn.to/4s0cUhk",
    rating: 3.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 42,
    title: "Gecko Run Marble Run Starter Set by Thames & Kosmos, Toy of The Year Winner - 63 Piece Vertical Marble Run, Flexible Tracks | Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads, Creative Play",
    price: "$18.08",
    originalPrice: "$34.95",
    image: "https://m.media-amazon.com/images/I/81QmsYdK-aL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/414qtS3",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 43,
    title: "Blue Marble Bouncy Ball Science Kit - Make Up to 45 Glow in The Dark Bouncy Balls for Kids with 6 Colors & 5 Mold Shapes, DIY STEM Projects, Science Kit, Kids Science Projects",
    price: "$13.49",
    originalPrice: "$15.99",
    image: "https://m.media-amazon.com/images/I/81NFdbarawL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4uZ0oBC",
    rating: 4.2,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 44,
    title: "VTech Marble Rush 3-Point Launch Set with Mini Basketball Hoop",
    price: "$17.99",
    originalPrice: "$28.78",
    image: "https://m.media-amazon.com/images/I/61xx52qAdyL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3O3JFwi",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 45,
    title: "Ravensburger GraviTrax: Trampoline Accessory | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Accessory for 2019 Toy of The Year Finalist",
    price: "$6.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/51dQKrVj5cL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4sI5lxd",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 46,
    title: "Ravensburger GraviTrax: Spiral Accessory | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$7.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/51dVyRuT2QL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/3NLlzX8",
    rating: 4.8,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 47,
    title: "Ravensburger GraviTrax: Magnetic Cannon Accessory | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Accessory for 2019 Toy of The Year Finalist",
    price: "$7.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/51krhTYePaL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4m5VWNu",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 48,
    title: "Gecko Run Marble Run Rapid-Fire Launcher Expansion Pack | Thames & Kosmos, Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads, Hours of Creative Play",
    price: "$15.30",
    originalPrice: "$17.95",
    image: "https://m.media-amazon.com/images/I/71UwG2y+wjL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3Pu9KoR",
    rating: 4.8,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 49,
    title: "Rhode Island Novelty 45 Piece Marble Run",
    price: "$16.68",
    originalPrice: "$25.73",
    image: "https://m.media-amazon.com/images/I/61KZCgn-ocL._AC_SL1000_.jpg",
    amazonLink: "https://amzn.to/4t9ONhb",
    rating: 3.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 50,
    title: "Gecko Run Marble Run Flex-Corner Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads, Hours of Creative Play",
    price: "$12.56",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71t7A5jxptL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/410nMRu",
    rating: 3.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 51,
    title: "Ravensburger GraviTrax: Transfer Accessory | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$9.99",
    originalPrice: "$16.04",
    image: "https://m.media-amazon.com/images/I/71T8JbSz3DL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/41yMit0",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 52,
    title: "Gecko Run Marble Run Twister Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads for Hours of Creative Play",
    price: "$13.95",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71xQmhWiWxL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tgSWjz",
    rating: 4.1,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 53,
    title: "Ravensburger GraviTrax Junior: Jump Element | Encourages Experimentation and Creativity | Globally Recognized Brand | Ideal for Kids Ages 3 and Up",
    price: "$8.39",
    originalPrice: "$10.31",
    image: "https://m.media-amazon.com/images/I/5158fHqZLpL._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/4tczuEq",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 54,
    title: "Ravensburger GraviTrax: Jumper Accessory | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$6.99",
    originalPrice: "$9.99",
    image: "https://m.media-amazon.com/images/I/71rfFEqgqaL._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/4dzS7xV",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 55,
    title: "Gecko Run Marble Run Speed-Kick Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads, Hours of Creative Play",
    price: "$14.95",
    originalPrice: "$19.07",
    image: "https://m.media-amazon.com/images/I/71epQyGKNaL._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/4sD2Uvz",
    rating: 3.9,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 56,
    title: "Gecko Run Marble Run Loop Expansion Pack by Thames & Kosmos - Extra Stunt for Vertical Marble Run Starter Set; Fast, No-Mess Setup with Residue-Free Nano-Adhesive Pads for Hours of Creative Play",
    price: "$13.95",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71Y6l4WrvQL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3QcVYHe",
    rating: 4.1,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 57,
    title: "Ravensburger GraviTrax: Loop Accessory | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Accessory for 2019 Toy of The Year Finalist",
    price: "$9.99",
    originalPrice: "$15.99",
    image: "https://m.media-amazon.com/images/I/61w5sLWm4GL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4djw3aB",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 58,
    title: "Learning Resources STEM Explorers Marble Runners - 18 Pieces, Ages 5+ STEM Toys and Activities for Kids, Brain Teaser Toys and Games, Kindergarten Games",
    price: "$16.49",
    originalPrice: "$20.99",
    image: "https://m.media-amazon.com/images/I/81g3gw2rUxL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bYJBWJ",
    rating: 3.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 59,
    title: "Gecko Run Marble Run Snake Expansion Pack by Thames & Kosmos - Extra Zigzag Maze for Vertical Marble Run Starter Set; Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads for Hours of Creative Play",
    price: "$13.95",
    originalPrice: "$14.95",
    image: "https://m.media-amazon.com/images/I/71RKWsjgdOL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3NSVG7S",
    rating: 4.1,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 60,
    title: "Sunny Days Entertainment TOYMENDOUS 50 Piece Marbles - Colorful Glass Marble for Kids Games | 49 Player Marbles and 1 Shooter",
    price: "$3.84",
    originalPrice: "$4.99",
    image: "https://m.media-amazon.com/images/I/8185pfa1+RL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3OhA6df",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 61,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - Construction Set with 15 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$36.17",
    originalPrice: "$37.99",
    image: "https://m.media-amazon.com/images/I/91PPS5Nb5LL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tdOi5K",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 62,
    title: "National Geographic Magnetic Marble Run - 75-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project",
    price: "$42.58",
    originalPrice: "$44.99",
    image: "https://m.media-amazon.com/images/I/91w6fC9vIZL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/417mHHK",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 63,
    title: "National Geographic Marble Run with Motorized Elevator - 95-Piece Marble Maze Kit with Motorized Spiral Lift, 20 Marbles, Perpetual Motion Machine, STEM Gifts for Boys and Girls, Kids Physics Toys",
    price: "$29.49",
    originalPrice: "$34.99",
    image: "https://m.media-amazon.com/images/I/915k6RmVXEL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bQjlNW",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 64,
    title: "TOMY Screwball Scramble Level Up Marble Maze - Vertical Beat-The-Clock Marble Run Game - Skill & Dexterity Challenge - 1-4 Players - Ages 5+",
    price: "$27.17",
    originalPrice: "$28.99",
    image: "https://m.media-amazon.com/images/I/710sFcAe6eL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v5kmuv",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 65,
    title: "National Geographic Marble Run with Motorized Elevator - 150-Piece Marble Maze Kit with Motorized Spiral Lift, 30 Marbles, Storage Bag & More, Perpetual Motion Machine, Kids Physics Toys",
    price: "$37.49",
    originalPrice: "$49.99",
    image: "https://m.media-amazon.com/images/I/91SOwfn94dL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dhDu1Y",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 66,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - Construction Set with 15 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$36.17",
    originalPrice: "$37.99",
    image: "https://m.media-amazon.com/images/I/91PPS5Nb5LL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4c5IhBv",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 67,
    title: "National Geographic Marble Run with Motorized Elevator - 95-Piece Marble Maze Kit with Motorized Spiral Lift, 20 Marbles, Perpetual Motion Machine, STEM Gifts for Boys and Girls, Kids Physics Toys",
    price: "$29.49",
    originalPrice: "$34.99",
    image: "https://m.media-amazon.com/images/I/915k6RmVXEL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4vaPxoq",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 68,
    title: "Ravensburger GraviTrax Starter Set - Gravity & Magnetic Marble Game - MESH Accredited STEM Toy for Kids - Brain-Building, Educational Gift - Engages Critical Thinking, Problem Solving - Ages 8+",
    price: "$48.99",
    originalPrice: "$69.99",
    image: "https://m.media-amazon.com/images/I/616rhJ28XoL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4tH9EsP",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 69,
    title: "Magnetic Marble Run, Assorted Colors, 9.6 W x 11.2 H Magnetic Board, 34 Pieces",
    price: "$34.94",
    originalPrice: "$34.94",
    image: "https://m.media-amazon.com/images/I/71FhgmokFqL._SL1500_.jpg",
    amazonLink: "https://amzn.to/4m1GuBQ",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 70,
    title: "Rhode Island Novelty 45 Piece Marble Run",
    price: "$22.25",
    originalPrice: "$22.25",
    image: "https://m.media-amazon.com/images/I/61KZCgn-ocL._AC_SL1000_.jpg",
    amazonLink: "https://amzn.to/41FW5O5",
    rating: 3.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 71,
    title: "VTech Marble Rush Raceway Set",
    price: "$34.29",
    originalPrice: "$35.99",
    image: "https://m.media-amazon.com/images/I/719sqWzU6WL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4c1gSAm",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 72,
    title: "National Geographic Magnetic Marble Run - 75-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project",
    price: "$42.58",
    originalPrice: "$44.99",
    image: "https://m.media-amazon.com/images/I/91w6fC9vIZL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v5mvX5",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 73,
    title: "Ravensburger GraviTrax: Trax Expansion Set | Enhance Your Marble Run Experience | STEM Toy for Kids Ages 8 and Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$20.99",
    originalPrice: "$29.99",
    image: "https://m.media-amazon.com/images/I/611AZddpQqL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/417WEjE",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 74,
    title: "Gecko Run Marble Run Challenge Edition by Thames & Kosmos | Vertical Marble Run w/Flexible Tracks, No-Mess Setup | Challenge Cards for a Head-to-Head Engineering Design Game for Teams or Solo Play",
    price: "$44.53",
    originalPrice: "$69.95",
    image: "https://m.media-amazon.com/images/I/81pdRMbOqtL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4c1ASms",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 75,
    title: "VTech Marble Rush Launchpad Set",
    price: "$41.99",
    originalPrice: "$46.66",
    image: "https://m.media-amazon.com/images/I/81Mz6wtYjbS._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/47vN7GI",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 76,
    title: "ThinkFun Gravity Maze - Falling Marble Logic Game - Challenging STEM Toy for Kids 8-12 - Gravity Marble Maze - Brain-Building Fun - Educational Gift - Boosts Critical Thinking & Problem Solving",
    price: "$22.75",
    originalPrice: "$29.99",
    image: "https://m.media-amazon.com/images/I/81iwJf07veL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dWUF9h",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 77,
    title: "National Geographic Glowing Marble Run - 115 Piece Construction Set with 25 Glow in The Dark Glass Marbles, Storage Bag, Great Creative STEM Toy for Girls and Boys",
    price: "$32.39",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/91DeE+gskAL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/47xl5un",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 78,
    title: "Ravensburger GraviTrax Junior Extension - Multi Routes | Expandable Marble Run | Boost Motor Skills & Creativity | Ages 3+",
    price: "$24.49",
    originalPrice: "$34.99",
    image: "https://m.media-amazon.com/images/I/61KD3qSiHwL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/3PKbb2v",
    rating: 4.9,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 79,
    title: "Ravensburger GraviTrax: Lifter Expansion Set | Marble Run & STEM Toy for Boys & Girls Ages 8 & Up | Compatible with All GraviTrax Systems | Ranked No.1 Marble Run System in The U.S",
    price: "$20.99",
    originalPrice: "$29.99",
    image: "https://m.media-amazon.com/images/I/61kMgAfOC3L._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4djBWEJ",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 80,
    title: "Ravensburger GraviTrax PRO: Vertical Expansion Set - Advanced Marble Run STEM Toy | Encourages Experimentation and Creativity | Compatible with All GraviTrax Systems | Gift for Kids Ages 8+",
    price: "$23.09",
    originalPrice: "$32.99",
    image: "https://m.media-amazon.com/images/I/61i0ff1UnWL._AC_SL1024_.jpg",
    amazonLink: "https://amzn.to/4v5foxK",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 81,
    title: "National Geographic Magnetic Marble Run - 150-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project (Amazon Exclusive)",
    price: "$59.49",
    originalPrice: "$79.99",
    image: "https://m.media-amazon.com/images/I/71LmJAu6hqL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tofIpL",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 82,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - 250 Piece Construction Set with 50 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$89.99",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/91ClLMT4eKL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v2Gg1k",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 83,
    title: "VTech Marble Rush T-Rex Dino Thrill Track Set",
    price: "$56.75",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/81u2cy5X0aL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dttqTL",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 84,
    title: "VTech Marble Rush Ultimate Set",
    price: "$56.35",
    originalPrice: "$64.99",
    image: "https://m.media-amazon.com/images/I/81itE4jtCuS._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4dWuy28",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 85,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - 250 Piece Construction Set with 50 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$89.99",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/91ClLMT4eKL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/47CdWsR",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 86,
    title: "National Geographic Magnetic Marble Run - 150-Piece STEM Building Set for Kids & Adults with Magnetic Track & Trick Pieces & Marbles for Building A Marble Maze, STEM Project (Amazon Exclusive)",
    price: "$59.49",
    originalPrice: "$79.99",
    image: "https://m.media-amazon.com/images/I/71LmJAu6hqL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3NZetOD",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 87,
    title: "NATIONAL GEOGRAPHIC Glowing Marble Run - 150 Piece Construction Set with 30 Glow in The Dark Glass Marbles & Storage Bag, STEM Gifts for Boys and Girls, Building Project Toy (Amazon Exclusive)",
    price: "$69.99",
    originalPrice: "$69.99",
    image: "https://m.media-amazon.com/images/I/91860gHgYyL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4v3FeCb",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 88,
    title: "VTech Marble Rush Ultimate Set",
    price: "$56.35",
    originalPrice: "$64.99",
    image: "https://m.media-amazon.com/images/I/81itE4jtCuS._AC_SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/47vR0LO",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 89,
    title: "Ravensburger GraviTrax: XXL Starter Set | Innovative Marble Run & STEM Toy for Kids | Engaging & Educational Building Game",
    price: "$90.99",
    originalPrice: "$129.99",
    image: "https://m.media-amazon.com/images/I/81Ek+9EbdaL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bXLhj8",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 90,
    title: "Ravensburger GraviTrax PRO Starter Set - Gravity & Magnetic Marble Game - MESH Accredited STEM Toy for Kids - Brain-Building, Educational Gift - Engages Critical Thinking, Problem Solving - Ages 8+",
    price: "$73.92",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/81h9dYmyHKL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4cjMTVF",
    rating: 4.6,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 91,
    title: "Gecko Run Marble Run Deluxe Starter Set by Thames & Kosmos - Vertical Marble Run w/Flexible Tracks, Loop & Trampoline Tricks, Fast, No-Mess Setup, Residue-Free Nano-Adhesive Pads for Creative Play",
    price: "$59.06",
    originalPrice: "$59.06",
    image: "https://m.media-amazon.com/images/I/817GMPZTb9L._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4ciXpfQ",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 92,
    title: "VTech Marble Rush T-Rex Dino Thrill Track Set",
    price: "$56.75",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/81u2cy5X0aL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3NZTnQm",
    rating: 4.5,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 93,
    title: "The Learning Journey: Techno Gears Marble Mania - Extreme Glo (200+ pcs) - Glow in The Dark Marble Run for Kids Ages 8-14 Years - Award Winning Toys",
    price: "$59.99",
    originalPrice: "$59.99",
    image: "https://m.media-amazon.com/images/I/91OsGJMwePL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4tqpEza",
    rating: 4.0,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 94,
    title: "K'NEX - Marble Coaster Run with Motor, 504 Pieces, STEM Building, Kid Construction Set, Ages 8+",
    price: "$63.99",
    originalPrice: "$63.99",
    image: "https://m.media-amazon.com/images/I/81crDO2gKxL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4bYSTlz",
    rating: 4.2,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 95,
    title: "Ravensburger GraviTrax PRO Starter-Set Drop'n'Roll. Interactive Marble Run System, Construction Toy for Children from 8 Years. Can be Combined with All Product Lines",
    price: "$82.50",
    originalPrice: "$99.99",
    image: "https://m.media-amazon.com/images/I/81jP1I+mbbL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3PMeSEK",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 96,
    title: "Ravensburger GraviTrax Junior Starter Set XXL - My Planet - Fun and Educational Preschool Marble Run Building Experience - STEM-Friendly, Interactive Learning, MESH Accredited - Kids Age 3 and Older",
    price: "$81.89",
    originalPrice: "$129.99",
    image: "https://m.media-amazon.com/images/I/91rPF4iPc9L._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4m43QqD",
    rating: 4.8,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 97,
    title: "Hape Wooden Quadrilla Super Spirals Marble Run STEM Toy for Kids 4+ Years",
    price: "$149.99",
    originalPrice: "$149.99",
    image: "https://m.media-amazon.com/images/I/617vGgKJ8NL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/41G34qh",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 98,
    title: "Hape Wooden Quadrilla Marble Run Vertigo Construction with Instruction | 134-PIECE STEM Educational Learning Toys for Kids",
    price: "$89.99",
    originalPrice: "$89.99",
    image: "https://m.media-amazon.com/images/I/61eOMEhNyrL._AC_SL1195_.jpg",
    amazonLink: "https://amzn.to/4t50vud",
    rating: 4.4,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 99,
    title: "ROKR 3D Wooden Puzzles for Adults Marble Run Model Building Kit(LGA01 Marble Night City)",
    price: "$70.37",
    originalPrice: "$70.37",
    image: "https://m.media-amazon.com/images/I/81diukhc-UL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/4ckF7Le",
    rating: 4.3,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
  {
    id: 100,
    title: "Ravensburger - GraviTrax - Speed Starter Set (185 Pieces) - Marble Run - Creative Construction Toy - Build-Your-Own Marble Track - Ages 8 and Up",
    price: "$111.63",
    originalPrice: "$111.63",
    image: "https://m.media-amazon.com/images/I/81iEVe-sEjL._AC_SL1500_.jpg",
    amazonLink: "https://amzn.to/3PNuTKE",
    rating: 4.7,
    reviews: 3420,
    category: "Toys & Games",
    badge: null,
    currency: "USD",
  },
];

export const categories = ["All", ...new Set(products.map((p) => p.category))];